name: Convert XLS to CSV and JSON

on:
  workflow_dispatch:
    inputs:
      xlsFile:
        description: 'XLS file with test data'
        required: true

jobs:
  Convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: |
        cd /tmp &&\
        wget https://github.com/hl7au/au-fhir-test-data-utils/releases/latest/download/xls-converter.zip &&\
        unzip xls-converter.zip &&\
        pip install xls_converter* &&\
        rm -rf xls_converter* xls-converter.zip
    - run: python -m xls_converter.main ${{ github.event.inputs.xlsFile }} testdata-csv
    - name: Install deps
      uses: ./.github/deps
    - name: Convert to json
      uses: ./.github/fhirmapping
