name: Convert CSV to JSON

on:
  workflow_dispatch

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install deps
      uses: ./.github/deps
    - name: Convert to json
      uses: ./.github/fhirmapping
    - id: git-diff-action
      run: echo "changed=$(git status --porcelain=v1 2>/dev/null | wc -l | tr -d '[:space:]')" >> "$GITHUB_OUTPUT"
    - if: steps.git-diff-action.outputs.changed != '0'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update generated files
  Protect Master:
    runs-on: ubuntu-latest
    needs: Convert
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Do not run on master branch
        run: echo "Convert actions should not run on master branch" && exit 1