# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on: push

jobs:
  Build:
    strategy:
      matrix:
        program: [Csv2FhirMapping, TestDataClient]
        os: [win, linux]
        arch: [x64, arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build ${{ matrix.program }} on ${{ matrix.os }}
      run: |
        dotnet publish Sparked.${{ matrix.program }}/Sparked.${{ matrix.program }}.csproj \
               --arch ${{ matrix.arch }} \
               --os ${{ matrix.os }} \
               --configuration Release \
               -p:PublishSingleFile=True \
               --framework net70 \
               --self-contained true \
               --output "Sparked.${{ matrix.program }}-${{ matrix.os }}Output"
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.program }}-${{ matrix.os }}-binaries
        path: |
          Sparked.${{ matrix.program }}-${{ matrix.os }}Output
